"""add agent_permission_grants table

Revision ID: 1130f09ac23e
Revises: a775484202cd
Create Date: 2026-08-20 23:32:30.059066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1130f09ac23e'
down_revision: Union[str, Sequence[str], None] = 'a775484202cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_permission_grants',
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'permission_id', name='uq_agent_permission_grant')
    )
    op.create_index(op.f('ix_agent_permission_grants_agent_id'), 'agent_permission_grants', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_permission_grants_permission_id'), 'agent_permission_grants', ['permission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_permission_grants_permission_id'), table_name='agent_permission_grants')
    op.drop_index(op.f('ix_agent_permission_grants_agent_id'), table_name='agent_permission_grants')
    op.drop_table('agent_permission_grants')
    # ### end Alembic commands ###
