"""add policy_rules table

Revision ID: 1e3915400f78
Revises: f4518537ff8c
Create Date: 2026-08-20 19:36:03.901525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3915400f78'
down_revision: Union[str, Sequence[str], None] = 'f4518537ff8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_rules',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'connector_type', 'action', name='uq_policy_rule_scope')
    )
    op.create_index(op.f('ix_policy_rules_tenant_id'), 'policy_rules', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_rules_tenant_id'), table_name='policy_rules')
    op.drop_table('policy_rules')
    # ### end Alembic commands ###
