"""add agents table, agent scoping on policy_rules and approval_requests

Revision ID: 243ee6114f35
Revises: 1e3915400f78
Create Date: 2026-08-20 19:45:24.613261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '243ee6114f35'
down_revision: Union[str, Sequence[str], None] = '1e3915400f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_api_key_hash'), 'agents', ['api_key_hash'], unique=True)
    op.create_index(op.f('ix_agents_tenant_id'), 'agents', ['tenant_id'], unique=False)
    op.add_column('approval_requests', sa.Column('agent_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_approval_requests_agent_id'), 'approval_requests', ['agent_id'], unique=False)
    op.create_foreign_key(None, 'approval_requests', 'agents', ['agent_id'], ['id'], ondelete='SET NULL')
    op.add_column('policy_rules', sa.Column('agent_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('uq_policy_rule_scope'), 'policy_rules', type_='unique')
    op.create_index(op.f('ix_policy_rules_agent_id'), 'policy_rules', ['agent_id'], unique=False)
    op.create_index('uq_policy_rule_agent_scoped', 'policy_rules', ['tenant_id', 'connector_type', 'action', 'agent_id'], unique=True, postgresql_where=sa.text('agent_id IS NOT NULL'))
    op.create_index('uq_policy_rule_tenant_wide', 'policy_rules', ['tenant_id', 'connector_type', 'action'], unique=True, postgresql_where=sa.text('agent_id IS NULL'))
    op.create_foreign_key(None, 'policy_rules', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'policy_rules', type_='foreignkey')
    op.drop_index('uq_policy_rule_tenant_wide', table_name='policy_rules', postgresql_where=sa.text('agent_id IS NULL'))
    op.drop_index('uq_policy_rule_agent_scoped', table_name='policy_rules', postgresql_where=sa.text('agent_id IS NOT NULL'))
    op.drop_index(op.f('ix_policy_rules_agent_id'), table_name='policy_rules')
    op.create_unique_constraint(op.f('uq_policy_rule_scope'), 'policy_rules', ['tenant_id', 'connector_type', 'action'], postgresql_nulls_not_distinct=False)
    op.drop_column('policy_rules', 'agent_id')
    op.drop_constraint(None, 'approval_requests', type_='foreignkey')
    op.drop_index(op.f('ix_approval_requests_agent_id'), table_name='approval_requests')
    op.drop_column('approval_requests', 'agent_id')
    op.drop_index(op.f('ix_agents_tenant_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_api_key_hash'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
