"""add agent_credential_grants table

Revision ID: a775484202cd
Revises: 7686a28e6f9c
Create Date: 2026-08-20 21:03:45.290712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a775484202cd'
down_revision: Union[str, Sequence[str], None] = '7686a28e6f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_credential_grants',
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'credential_id', name='uq_agent_credential_grant')
    )
    op.create_index(op.f('ix_agent_credential_grants_agent_id'), 'agent_credential_grants', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_credential_grants_credential_id'), 'agent_credential_grants', ['credential_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_credential_grants_credential_id'), table_name='agent_credential_grants')
    op.drop_index(op.f('ix_agent_credential_grants_agent_id'), table_name='agent_credential_grants')
    op.drop_table('agent_credential_grants')
    # ### end Alembic commands ###
