"""add notification_repo to tenants and approval_requests

Revision ID: fae57e4eeed1
Revises: ba2865050d34
Create Date: 2026-08-20 05:34:45.028257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae57e4eeed1'
down_revision: Union[str, Sequence[str], None] = 'ba2865050d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_requests', sa.Column('notification_repo', sa.String(length=200), nullable=True))
    op.add_column('approval_requests', sa.Column('notification_issue_number', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('notification_repo', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'notification_repo')
    op.drop_column('approval_requests', 'notification_issue_number')
    op.drop_column('approval_requests', 'notification_repo')
    # ### end Alembic commands ###
