import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowUpRight, ArrowRight, ShieldCheck, Bot, Activity, Clock3, Check, Plug, GitBranch, Mail, MessageSquare, RefreshCw, Fingerprint, LockKeyhole } from 'lucide-react'
import { apiClient, apiErrorMessage } from '../api/client'
interface Overview {active_agents:number;active_connectors:number;pending_approvals:number;decisions_24h:number;blocked_24h:number;succeeded_24h:number;unknown:number;connectors:{type:string;configured:boolean;actions:number}[]}
interface Event {id:string;action:string;connector_type:string;decision:string;created_at:string;agent_name:string|null;decision_source:string}
export function DashboardHomePage() {
 const [data,setData]=useState<Overview|null>(null),[events,setEvents]=useState<Event[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true)
 async function load(){setLoading(true);setError('');try{const [o,a]=await Promise.all([apiClient.get<Overview>('/tenant/overview'),apiClient.get<Event[]>('/tenant/audit?limit=5')]);setData(o.data);setEvents(a.data)}catch(e){setError(apiErrorMessage(e,'Veriler yüklenemedi. Bağlantınızı kontrol edip tekrar deneyin.'))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const metrics=[{label:'Ajan kararları',value:data?.decisions_24h,caption:'Son 24 saat',icon:Activity},{label:'Onay bekleyen',value:data?.pending_approvals,caption:'İnsan kararı gerekiyor',icon:Clock3},{label:'Engellenen eylem',value:data?.blocked_24h,caption:'Son 24 saat · policy kararı',icon:ShieldCheck},{label:'Aktif ajan',value:data?.active_agents,caption:'Workspace genelinde',icon:Bot}]
 return <div className="overview-page">
   <div className="page-heading"><div><div className="eyebrow"><span/> AGENT GOVERNANCE PLATFORM</div><h1>Otonomiye alan açın.<br/><span>Kontrolü elinizde tutun.</span></h1><p>AI ajanlarınızın ne yapabildiğini, neyi beklediğini ve nedenini görün.</p></div><button className="outline-action" onClick={()=>void load()} disabled={loading}><RefreshCw size={15} className={loading?'animate-spin':''}/> Yenile</button></div>
   {error && <div role="alert" className="error-banner">{error}</div>}
   <div className="metrics-grid">{metrics.map(({label,value,caption,icon:Icon})=><div className="metric-card" key={label}><div><span>{label}</span><Icon size={17}/></div><strong>{value === undefined ? '—' : value}</strong><small>{caption}</small></div>)}</div>
   <div className="overview-middle"><section className="control-card"><div className="card-eyebrow">GÜVENLİ BAŞLANGIÇ <span>03 ADIM</span></div><h2>İlk ajanınızı <br/>güvenle devreye alın.</h2><p>Bir servis bağlayın, ajan kimliği oluşturun ve yalnız ihtiyaç duyduğu kaynaklara izin verin.</p><div className="onboarding-steps">{[{to:'/integrations',n:'01',title:'Servisinizi bağlayın',sub:'Gmail, GitHub veya Slack',done:(data?.active_connectors??0)>0},{to:'/agents',n:'02',title:'Ajan kimliğini oluşturun',sub:'Ayrı kimlik, açık izinler',done:(data?.active_agents??0)>0},{to:'/policies',n:'03',title:'Politikalarınızı inceleyin',sub:'İzin ver · Onay iste · Engelle',done:false}].map(s=><Link to={s.to} key={s.n}><span className={'step-number '+(s.done?'done':'')}>{s.done?<Check size={15}/>:s.n}</span><div><strong>{s.title}</strong><small>{s.sub}</small></div><ArrowUpRight size={16}/></Link>)}</div><Link to="/agents" className="lime-action">Ajanları yönet <ArrowRight size={16}/></Link></section>
   <section className="decision-card"><div className="section-heading"><div><span className="eyebrow">ENFORCEMENT AKIŞI</span><h2>Her eylemin bir karar yolu var.</h2></div><ShieldCheck size={20}/></div><div className="enforcement-path"><div><Bot size={21}/><strong>Ajan</strong><small>Aksiyon isteği</small></div><span className="path-line"/><div className="guard-node"><ShieldCheck size={25}/><strong>AgentGuard</strong><small>Kimlik · Kapsam · Policy</small></div><span className="path-line"/><div><Plug size={21}/><strong>Servis</strong><small>Yetkili yürütme</small></div></div><div className="decision-outcomes"><div><span className="outcome-dot allowed"/> İzin ver<small>Kapsam içinde çalıştır</small></div><div><span className="outcome-dot pending"/> Onay iste<small>İnsan kararını bekle</small></div><div><span className="outcome-dot denied"/> Engelle<small>Eylemi durdur</small></div></div><div className="assurance-row"><span><Fingerprint size={15}/> Ajan bazlı erişim</span><span><LockKeyhole size={15}/> Şifreli payload</span></div></section></div>
   <section className="activity-card"><div className="section-heading"><div><h2>Son kararlar</h2><p>Workspace'inizdeki gerçek eylem kayıtları.</p></div><Link to="/audit">Denetim kayıtları <ArrowUpRight size={14}/></Link></div><div className="table-scroll"><table><thead><tr><th>EYLEM</th><th>AJAN / KAYNAK</th><th>KARAR</th><th>ZAMAN</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td><strong>{e.action}</strong><small>{e.connector_type}</small></td><td>{e.agent_name??'İnsan isteği'}</td><td><span className={'decision-pill '+e.decision.toLowerCase()}>{e.decision==='ALLOW'?'İzin verildi':e.decision==='DENY'?'Engellendi':'Onay gerekiyor'}</span></td><td>{new Date(e.created_at).toLocaleTimeString('tr-TR')}</td></tr>)}</tbody></table></div>{!loading && !error && events.length===0 && <div className="honest-empty"><Activity size={25}/><strong>Henüz bir eylem kaydedilmedi</strong><p>İlk ajan isteğinizden sonra kararlar burada görünecek.</p><Link to="/integrations">İlk bağlantıyı oluştur <ArrowRight size={14}/></Link></div>}</section>
   <div className="connector-strip"><span>MEVCUT CONNECTOR'LAR</span>{data?.connectors.map(c=>{const Icon=c.type==='github'?GitBranch:c.type==='gmail'?Mail:MessageSquare;return <Link to="/integrations" key={c.type}><Icon size={18}/><strong>{c.type==='github'?'GitHub':c.type==='gmail'?'Gmail':'Slack'}</strong><small>{c.configured?'OAuth hazır':'OAuth kurulumu gerekli'}</small><ArrowUpRight size={14}/></Link>})}</div>
 </div>
}
