import { useEffect, useState } from 'react'
import { Activity, RefreshCw, Search, Copy } from 'lucide-react'
import { apiClient, apiErrorMessage } from '../api/client'
interface Operation {id:string;action:string;status:string;created_at:string;decision_source:string;error:string|null;payload_hash:string}
const labels:Record<string,string>={WAITING:'Onay bekliyor',READY:'Hazır',EXECUTING:'Yürütülüyor',SUCCEEDED:'Tamamlandı',UNKNOWN:'Sonuç belirsiz',FAILED:'Başarısız',DENIED:'Engellendi',EXPIRED:'Süresi doldu'}
export function ExecutionsPage(){
 const [rows,setRows]=useState<Operation[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[status,setStatus]=useState('')
 async function load(){setLoading(true);try{const {data}=await apiClient.get<Operation[]>('/tenant/operations');setRows(data);setError('')}catch(e){setError(apiErrorMessage(e))}finally{setLoading(false)}}
 useEffect(()=>{void load();const t=setInterval(()=>void load(),10000);return()=>clearInterval(t)},[])
 const visible=rows.filter(r=>(!status||r.status===status)&&(r.action.includes(query)||r.id.includes(query)))
 return <div className="overview-page"><div className="page-heading compact"><div><div className="eyebrow">EXECUTION LEDGER</div><h1>İşlem geçmişi</h1><p>Bir onay kararı ile gerçekten tamamlanan eylemi birbirinden ayırın.</p></div><button className="outline-action" onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div><div className="notice-card"><Activity size={20}/><div><strong>Belirsiz sonuçlar otomatik tekrar çalıştırılmaz.</strong><p>UNKNOWN durumunda sağlayıcıdaki sonucu doğrulayın. Aynı idempotency anahtarı mevcut işlemi döndürür.</p></div></div><div className="filter-bar"><label><Search size={16}/><input aria-label="İşlem ara" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Eylem veya işlem kimliği ara…"/></label><select aria-label="Durum filtresi" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tüm durumlar</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><span>En son 100 işlem</span></div>{error&&<div role="alert" className="error-banner">{error}</div>}<section className="activity-card"><div className="table-scroll"><table><thead><tr><th>EYLEM / İŞLEM KİMLİĞİ</th><th>DURUM</th><th>KARAR KAYNAĞI</th><th>OLUŞTURULDU</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><strong>{r.action}</strong><small><button title="İşlem kimliğini kopyala" onClick={()=>void navigator.clipboard.writeText(r.id)} className="copy-inline">{r.id.slice(0,8)}… <Copy size={11}/></button></small></td><td><span className={'decision-pill '+(r.status==='SUCCEEDED'?'allow':r.status==='UNKNOWN'?'deny':'require_approval')}>{labels[r.status]??r.status}</span>{r.error&&<small>{r.error}</small>}</td><td>{r.decision_source}</td><td>{new Date(r.created_at).toLocaleString('tr-TR')}</td></tr>)}</tbody></table></div>{!loading&&visible.length===0&&<div className="honest-empty"><Activity size={26}/><strong>Gösterilecek işlem yok</strong><p>Filtrelerinizi değiştirin veya ilk ajan eyleminizi başlatın.</p></div>}</section></div>
}
